# Travis-CI Build
# see travis-ci.org for details

language: c

install:
 # Make sure mono is installed,
 # pipe stdout to dev/null because qq is still too chatty
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -qq mono-devel > /dev/null

script:
 - ./mono-build.sh 
 - ./upload-bin.sh
 - ./test-push.sh

branches:
 only:
  - master

env:
 global:
  - secure: "jYGWDQjwQtM1UShxkJ/a+j3vn/AMzmxOdE0iQ+n/zed4U8F3B/Za0zbomKdC\nQUZN5WoVZ7aqR+SjXprDRVml11m7i4bQEetAyy5/A1GvE93YxWQNdMwI2sTe\n8uLpix1jYulipodJ3oMyQXlvJ8g4mOO29ZLtlNpMtYuIUKZhJJc="
